### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by snowformatics** [bhosking/bitepi-python#1]
Hi,

Thanks for sharing BitEpi! I would like to try your software directly via Python, how can I install it?

I cloned your project and when I run it, I get the following error:

Traceback (most recent call last):
  File "C:/Users/x/PycharmProjects/bitepi-python/bitepimodule/run.py", line 23, in <module>
    best_ig=True,
  File "C:\Users\x\PycharmProjects\bitepi-python\bitepimodule\bitepi.py", line 203, in compute_epistasis
    return_code = bitepi(delimiter, argstring)
TypeError: 'module' object is not callable

Thanks a lot in advance
Stefanie

**Comment by bhosking** [comment]
Hi Stefanie,

This is a python wrapper for the bitepi project, and should be imported as a python package. `pip3 install bitepi` should install the package (along with numpy and pandas if they aren't already installed) which can then be used inside a python interpreter, script or notebook by first calling `import bitepi` before creating an instance of `bitepi.Epistasis` as described in the readme.
